const colors = [
    { name: 'Blue', hex: '#2196f3' },
    { name: 'Green', hex: '#4caf50' },
    { name: 'Purple', hex: '#9c27b0' },
    { name: 'Pink', hex: '#e91e63' },
    { name: 'Orange', hex: '#ff9800' },
    { name: 'Yellow', hex: '#ffeb3b' },
    { name: 'Red', hex: '#f44336' },
    { name: 'Brown', hex: '#795548' },
    { name: 'Gray', hex: '#9e9e9e' },
    { name: 'Gold', hex: '#ffd700' },
    { name: 'Silver', hex: '#c0c0c0' },
    { name: 'Dark Green', hex: '#006400' },
    { name: 'Deep Sky Blue', hex: '#1e90ff' },
    { name: 'Turquoise', hex: '#00ffff' },
    { name: 'Lavender', hex: '#e6e6fa' },
    { name: 'Coral', hex: '#ff7f50' },
    { name: 'Orchid', hex: '#da70d6' },
    { name: 'Olive Green', hex: '#556b2f' },
    { name: 'Salmon', hex: '#fa8072' },
    { name: 'Sky Blue', hex: '#87ceeb' },
    { name: 'Light Blue', hex: '#afeeee' },
    { name: 'Pink Orange', hex: '#ff69b4' },
    { name: 'Chocolate Brown', hex: '#d2691e' },
    { name: 'Teal', hex: '#008080' },
    { name: 'Crimson', hex: '#dc143c' },
    { name: 'Indigo', hex: '#4b0082' },
    { name: 'Magenta', hex: '#ff00ff' },
    { name: 'Lime', hex: '#00ff00' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Navy', hex: '#000080' },
    { name: 'Khaki', hex: '#f0e68c' },
    { name: 'Aqua', hex: '#00ffff' },
    { name: 'Slate Gray', hex: '#708090' }
];

export default colors